### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by yibuyisheng** [ecomfe/veui#3]
# Dialog

## props

* title 对话框标题
* ui reverse->对话框标题白底蓝字 normal->对话框标题蓝底白字（默认值）
* center 是否在浏览器视口居中显示
* top 对话框顶部到浏览器视口顶部的距离，可以是百分数，优先级高于center
* left 对话框到浏览器视口左侧的距离，可以是百分数，优先级高于center
* mask 是否需要遮罩层
* draggable 是否能拖拽
* closeVisible 是否展示关闭按钮
* visible 是否显示对话框
* height 高度
* width 宽度

## slots

* title

* \- 内容块

* foot

## events

* show
* hide
* sizechange
* positionchange

**Comment by otakustay** [comment]
> ui reverse->对话框标题白底蓝字 normal->对话框标题蓝底白字（默认值）

如果你想做通用开源的组件库的话，这种属性不合适吧……

> center 是否在浏览器视口居中显示

center会随着拖动而同步么？

另外zindex管理咋整？

**Comment by Justineo** [comment]
> 如果你想做通用开源的组件库的话，这种属性不合适吧……

灰大啥意思？

**Comment by chestnutchen** [comment]
目测上边大多数是`once`，用来初始化的属性而已，区分一下？

**Comment by otakustay** [comment]
> 灰大啥意思？

从属性上来看，这是一个样式属性，且只提供了2种样式，如果这是一个开放的通用的组件，而不是仅适用你们系统的话，我觉得样式上应该有更灵活的控制，为啥不能黄底绿字、红底黑字？

**Comment by Justineo** [comment]
这套 UI 是对 UE 的规范的实现，我目前的设计是，视觉相关的样式全都放在一个 `ui` 属性里边，类似原生的 `class`。扩展的方式可以有几种：

1. 写组件样式的时候提供 Less 变量，用户可以直接覆盖；
2. 在 Less 中覆盖已定义 `ui` 属性的样式；
3. 用户在调用时传入自定义的 `ui` 属性，并编写对应的样式。

拿这个来说，`Dialog` 可以自带默认样式和 `ui="reversed"` 时的样式，分别是：

```less
.veui-dialog-title {
  background-color: @veui-theme-color-primary;
  color: #fff;

  &[ui~="reversed"] {
    background-color: #fff;
    color: @veui-theme-color-primary;
  }
}
```

当然也可以进一步再抽象一层：

```less
@veui-dialog-bg-color: @veui-theme-color-primary;
@veui-dialog-text-color: #fff;
.veui-dialog-title {
  background-color: @veui-dialog-bg-color;
  color: @veui-dialog-text-color;

  &[ui~="reversed"] {
    background-color: @veui-dialog-text-color;
    color: @veui-dialog-bg-color;
  }
}
```

用户自定义时，比如黄底绿字，可以这么写：

重写变量：

```less
@veui-dialog-bg-color: yellow;
@veui-dialog-text-color: green;
```

或者重写默认 `ui`：

```less
.veui-dialog-title {
  &[ui~="reversed"] {
    background-color: yellow;
    color: green;
  }
}
```

或者自定义 `ui`：

```html
<veui-dialog ui="spring">...</veui-dialog>
```

```less
.veui-dialog-title {
  &[ui~="spring"] {
    background-color: yellow;
    color: green;
  }
}
```
