### ISSUE TITLE
Tabs 在 flex 布局容器内，溢出时行为异常

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui#537]
左侧div flex-shrink: 1 时，宽度缩小时 Tabs 出现异常。
左侧div flex-shrink: 0 时，添加 tab 溢出后 出现异常。

```html
<div class="main">
        <div class="aaa">
            <veui-tabs>
                <veui-tab :label="1" />
                <veui-tab :label="2" />
                <veui-tab :label="3" />
                <veui-tab :label="4" />
                <veui-tab :label="5" />
                <veui-tab :label="6" />
            </veui-tabs>
        </div>
        <div class="bbb"></div>
    </div>
```

```less
.main {
    display: flex;
    .aaa {
        flex: 2 1 600px;
    }
    .bbb {
        flex: 1 0 200px;
    }
}
```

![Screen Recording 2019-08-19 at 17 43 36](https://user-images.githubusercontent.com/1331413/63256129-89e10d80-c2a9-11e9-9aa8-84442cc9620e.gif)

**Comment by 599316527** [comment]
溢出时横向滚动按钮失效

![Screen Recording 2019-08-27 at 14 02 33](https://user-images.githubusercontent.com/1331413/63745150-12783300-c8d4-11e9-89a8-de39759d893b.gif)

PS. tab间、加tab按钮左侧 间距太大，浪费横向空间，希望增加 `micro` 样式。

**Comment by 599316527** [comment]
> 溢出时横向滚动按钮失效
> 
> ![Screen Recording 2019-08-27 at 14 02 33](https://user-images.githubusercontent.com/1331413/63745150-12783300-c8d4-11e9-89a8-de39759d893b.gif)
> 
> PS. tab间、加tab按钮左侧 间距太大，浪费横向空间，希望增加 `micro` 样式。

魔改了样式

```less
.veui-tabs[ui~=micro] {
    .veui-tabs-item {
        margin-left: 11px;
        &::before {
            content: "";
            display: inline-block;
            width: 1px;
            height: 14px;
            background-color: #e7e7e7;
            position: absolute;
            top: 10px;
            left: -6px;
        }
        button {
            padding: 0 4px;
        }
        .veui-tabs-item-remove {
            padding: 0;
        }

        &:first-child {
            margin-left: 0;
            button {
                padding-left: 0;
            }
            &::before {
                content: unset;
            }
        }
    }
    .veui-tabs-extra {
        button {
            margin-left: 6px;
        }
    }
    .veui-tabs-scroller {
        margin-left: 4px;
        button {
            margin-left: 0;
        }
    }
}
```
