### ISSUE TITLE
Carousel轮播图组件无法根据外部给定区域自动调整宽高大小

### ISSUE THREAD

**Issue by hblvsjtu** [ecomfe/veui#811]
【问题描述】Carousel轮播图组件没有办法根据外部给定区域自动调整宽高大小，`.veui-carousel-viewport`这个class宽高貌似是被写死的，无法自适应外部区域大小。
【环境版本】MacOS: 11.01；    chrome浏览器: 88.0.4324.192；    veui: 2.0.0-beta.27；    
【调用方法】如[官网demo](https://veui.dev/components/carousel)的调用方法，并在组件加上`width`和`height`的class，如：
```js
    import { Carousel } from 'veui';
    // 组件
    <veui-carousel
      class="carousel"
      :datasource="items"
    />
```
```css
    // 样式
    .carousel {
       width: 256px;
       height: 170px;
    }
```
【复现步骤】使用上述调用方式100%复现。
【预期效果】轮播图组件的大小适应外部class给定的宽高。
【实际效果】轮播图组件的大小为宽480px，高270px，无法自适应给定宽高。
